name: Create Pull Request for Flux Updates
on:
  push:
    branches:
     - fluxo/*
permissions:
  pull-requests: write
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Get Current Date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Get Current Branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi
      - name: Create Pull Request
        run: |
          gh pr create \
          --base "develop" \
          --head "${{ env.BRANCH_NAME }}" \
          --title "Deployment request for APP changed -  ${{ env.CURRENT_DATE }}" \
          --body "PR wants to deploy
          This pull request was automatically created by a GitHub Action.

          `quotes for code`
          More information"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
